# Generated by Django 4.2.7 on 2025-12-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
