# Generated by Django 4.2.7 on 2025-12-30 01:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El NIT debe contener entre 9 y 15 dígitos', regex='^\\d{9,15}$')], verbose_name='NIT')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'api_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('caracteristicas', models.TextField(verbose_name='Características')),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio USD')),
                ('precio_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio EUR')),
                ('precio_cop', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio COP')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='domain_layer.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'api_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('transaccion_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='Hash de Transacción (Blockchain)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='domain_layer.empresa', verbose_name='Empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='domain_layer.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'api_inventario',
                'ordering': ['-fecha_ingreso'],
                'unique_together': {('empresa', 'producto')},
            },
        ),
    ]
